name: Deploy Symfony Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Deploy application
        run: |
          # Add your deployment commands here
          # For example:
          # - Deploy your Symfony application to Scalingo

      - name: Run post-deployment tasks
        run: |
          # Run post-deployment tasks
          php bin/console your:php bin/console doctrine:migrations:migrate


